package com.example.studentloansystem.entity.enums;

public enum EducationLevel {
    ASSOCIATE,
    CONTINUOUS_BACHELORS,
    DISCONTINUOUS_BACHELORS,
    CONTINUOUS_MASTERS,
    DISCONTINUOUS_MASTER,
    PROFESSIONAL_DOCTORATE,
    CONTINUOUS_DOCTORATE,
    DISCONTINUOUS_SPECIALIZED_DOCTORATE

}
